#! bin/bash
set -e

export LC_ALL=zh_CN.GB2312;export LANG=zh_CN.GB2312

if [ -d ~/.MyPlug-ins ]
then
  rm -rf ~/.MyPlug-ins
  #echo "您已经安装了MyPlug-ins，正在移除~/.MyPlug-ins "
fi

echo "Cloning MyPlug-ins..."
hash git >/dev/null && /usr/bin/env git clone https://github.com/heyuan110/MyPlug-ins.git ~/.MyPlug-ins || {
  echo "git not installed"
  exit
}
echo "正在安装..."
cp -rf ~/.MyPlug-ins/* ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/
ls -l ~/.MyPlug-ins | grep '^d' | awk '{ print $9 }'
echo "安装完成,请重启XCODE！"